### PR TITLE
improve one page website

### PR DESCRIPTION
**Pull request by BigEd**

### CODE REVIEW

**Comment by BigEd** [comment]
oops - the spec.md file needs some markup tweaks to support this change.
see
https://revaldinho.github.io/opc/opc1spec.html

**Comment by BigEd** [comment]
should also re-insert a link on the front page back to the source on github?

previously:
<a href="https://github.com/revaldinho/opc">OPC project on GitHub</a>

**Comment by BigEd** [comment]
Have updated several files: have a look at
https://biged.github.io/opc/
Might need to tweak the theme, or remove it (use a # to comment out the theme in docs/_config.yml) to improve the appearance of the instruction set table.
The theme gives us a free link back to the repo - if we remove the theme, we should add in suitable links: from the front page to the repo, and from subpages back up to the front page.

**Comment by revaldinho** [comment]
Merged Ed's documentation changes into the master

**Pull request merged**
